// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: City.proto

package com.wx.dex.high.level.data_soruce.data.city.protobuf;

public final class CityModel {
  private CityModel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface _CityModelOrBuilder extends
      // @@protoc_insertion_point(interface_extends:_CityModel)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;string, ._CityModel._CityItem&gt; map = 1;</code>
     */
    int getMapCount();
    /**
     * <code>map&lt;string, ._CityModel._CityItem&gt; map = 1;</code>
     */
    boolean containsMap(
        String key);
    /**
     * Use {@link #getMapMap()} instead.
     */
    @Deprecated
    java.util.Map<String, _CityModel._CityItem>
    getMap();
    /**
     * <code>map&lt;string, ._CityModel._CityItem&gt; map = 1;</code>
     */
    java.util.Map<String, _CityModel._CityItem>
    getMapMap();
    /**
     * <code>map&lt;string, ._CityModel._CityItem&gt; map = 1;</code>
     */

    _CityModel._CityItem getMapOrDefault(
        String key,
        _CityModel._CityItem defaultValue);
    /**
     * <code>map&lt;string, ._CityModel._CityItem&gt; map = 1;</code>
     */

    _CityModel._CityItem getMapOrThrow(
        String key);
  }
  /**
   * Protobuf type {@code _CityModel}
   */
  public  static final class _CityModel extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:_CityModel)
      _CityModelOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use _CityModel.newBuilder() to construct.
    private _CityModel(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private _CityModel() {
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private _CityModel(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                map_ = com.google.protobuf.MapField.newMapField(
                    MapDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<String, _CityItem>
              map__ = input.readMessage(
                  MapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              map_.getMutableMap().put(
                  map__.getKey(), map__.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CityModel.internal_static__CityModel_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CityModel.internal_static__CityModel_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              _CityModel.class, Builder.class);
    }

    public interface _CityItemOrBuilder extends
        // @@protoc_insertion_point(interface_extends:_CityModel._CityItem)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>repeated string values = 1;</code>
       */
      java.util.List<String>
          getValuesList();
      /**
       * <code>repeated string values = 1;</code>
       */
      int getValuesCount();
      /**
       * <code>repeated string values = 1;</code>
       */
      String getValues(int index);
      /**
       * <code>repeated string values = 1;</code>
       */
      com.google.protobuf.ByteString
          getValuesBytes(int index);
    }
    /**
     * Protobuf type {@code _CityModel._CityItem}
     */
    public  static final class _CityItem extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:_CityModel._CityItem)
        _CityItemOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use _CityItem.newBuilder() to construct.
      private _CityItem(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private _CityItem() {
        values_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      }

      @Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private _CityItem(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                String s = input.readStringRequireUtf8();
                if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                  values_ = new com.google.protobuf.LazyStringArrayList();
                  mutable_bitField0_ |= 0x00000001;
                }
                values_.add(s);
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
            values_ = values_.getUnmodifiableView();
          }
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CityModel.internal_static__CityModel__CityItem_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CityModel.internal_static__CityModel__CityItem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                _CityItem.class, Builder.class);
      }

      public static final int VALUES_FIELD_NUMBER = 1;
      private com.google.protobuf.LazyStringList values_;
      /**
       * <code>repeated string values = 1;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getValuesList() {
        return values_;
      }
      /**
       * <code>repeated string values = 1;</code>
       */
      public int getValuesCount() {
        return values_.size();
      }
      /**
       * <code>repeated string values = 1;</code>
       */
      public String getValues(int index) {
        return values_.get(index);
      }
      /**
       * <code>repeated string values = 1;</code>
       */
      public com.google.protobuf.ByteString
          getValuesBytes(int index) {
        return values_.getByteString(index);
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        for (int i = 0; i < values_.size(); i++) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, values_.getRaw(i));
        }
        unknownFields.writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        {
          int dataSize = 0;
          for (int i = 0; i < values_.size(); i++) {
            dataSize += computeStringSizeNoTag(values_.getRaw(i));
          }
          size += dataSize;
          size += 1 * getValuesList().size();
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @Override
      public boolean equals(final Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof _CityItem)) {
          return super.equals(obj);
        }
        _CityItem other = (_CityItem) obj;

        boolean result = true;
        result = result && getValuesList()
            .equals(other.getValuesList());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (getValuesCount() > 0) {
          hash = (37 * hash) + VALUES_FIELD_NUMBER;
          hash = (53 * hash) + getValuesList().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static _CityItem parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static _CityItem parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static _CityItem parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static _CityItem parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static _CityItem parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static _CityItem parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static _CityItem parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static _CityItem parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static _CityItem parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static _CityItem parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static _CityItem parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static _CityItem parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(_CityItem prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @Override
      protected Builder newBuilderForType(
          BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code _CityModel._CityItem}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:_CityModel._CityItem)
          _CityItemOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return CityModel.internal_static__CityModel__CityItem_descriptor;
        }

        protected FieldAccessorTable
            internalGetFieldAccessorTable() {
          return CityModel.internal_static__CityModel__CityItem_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  _CityItem.class, Builder.class);
        }

        // Construct using com.wgllss.protobuf.CityModel._CityModel._CityItem.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          values_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000001);
          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return CityModel.internal_static__CityModel__CityItem_descriptor;
        }

        public _CityItem getDefaultInstanceForType() {
          return _CityItem.getDefaultInstance();
        }

        public _CityItem build() {
          _CityItem result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public _CityItem buildPartial() {
          _CityItem result = new _CityItem(this);
          int from_bitField0_ = bitField0_;
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            values_ = values_.getUnmodifiableView();
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.values_ = values_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof _CityItem) {
            return mergeFrom((_CityItem)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(_CityItem other) {
          if (other == _CityItem.getDefaultInstance()) return this;
          if (!other.values_.isEmpty()) {
            if (values_.isEmpty()) {
              values_ = other.values_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureValuesIsMutable();
              values_.addAll(other.values_);
            }
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          _CityItem parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (_CityItem) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private com.google.protobuf.LazyStringList values_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        private void ensureValuesIsMutable() {
          if (!((bitField0_ & 0x00000001) == 0x00000001)) {
            values_ = new com.google.protobuf.LazyStringArrayList(values_);
            bitField0_ |= 0x00000001;
           }
        }
        /**
         * <code>repeated string values = 1;</code>
         */
        public com.google.protobuf.ProtocolStringList
            getValuesList() {
          return values_.getUnmodifiableView();
        }
        /**
         * <code>repeated string values = 1;</code>
         */
        public int getValuesCount() {
          return values_.size();
        }
        /**
         * <code>repeated string values = 1;</code>
         */
        public String getValues(int index) {
          return values_.get(index);
        }
        /**
         * <code>repeated string values = 1;</code>
         */
        public com.google.protobuf.ByteString
            getValuesBytes(int index) {
          return values_.getByteString(index);
        }
        /**
         * <code>repeated string values = 1;</code>
         */
        public Builder setValues(
            int index, String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureValuesIsMutable();
          values_.set(index, value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string values = 1;</code>
         */
        public Builder addValues(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureValuesIsMutable();
          values_.add(value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string values = 1;</code>
         */
        public Builder addAllValues(
            Iterable<String> values) {
          ensureValuesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, values_);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string values = 1;</code>
         */
        public Builder clearValues() {
          values_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string values = 1;</code>
         */
        public Builder addValuesBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          ensureValuesIsMutable();
          values_.add(value);
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFieldsProto3(unknownFields);
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:_CityModel._CityItem)
      }

      // @@protoc_insertion_point(class_scope:_CityModel._CityItem)
      private static final _CityItem DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new _CityItem();
      }

      public static _CityItem getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<_CityItem>
          PARSER = new com.google.protobuf.AbstractParser<_CityItem>() {
        public _CityItem parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new _CityItem(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<_CityItem> parser() {
        return PARSER;
      }

      @Override
      public com.google.protobuf.Parser<_CityItem> getParserForType() {
        return PARSER;
      }

      public _CityItem getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int MAP_FIELD_NUMBER = 1;
    private static final class MapDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          String, _CityItem> defaultEntry =
              com.google.protobuf.MapEntry
              .<String, _CityItem>newDefaultInstance(
                  CityModel.internal_static__CityModel_MapEntry_descriptor,
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  _CityItem.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        String, _CityItem> map_;
    private com.google.protobuf.MapField<String, _CityItem>
    internalGetMap() {
      if (map_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            MapDefaultEntryHolder.defaultEntry);
      }
      return map_;
    }

    public int getMapCount() {
      return internalGetMap().getMap().size();
    }
    /**
     * <code>map&lt;string, ._CityModel._CityItem&gt; map = 1;</code>
     */

    public boolean containsMap(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      return internalGetMap().getMap().containsKey(key);
    }
    /**
     * Use {@link #getMapMap()} instead.
     */
    @Deprecated
    public java.util.Map<String, _CityItem> getMap() {
      return getMapMap();
    }
    /**
     * <code>map&lt;string, ._CityModel._CityItem&gt; map = 1;</code>
     */

    public java.util.Map<String, _CityItem> getMapMap() {
      return internalGetMap().getMap();
    }
    /**
     * <code>map&lt;string, ._CityModel._CityItem&gt; map = 1;</code>
     */

    public _CityItem getMapOrDefault(
        String key,
        _CityItem defaultValue) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, _CityItem> map =
          internalGetMap().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, ._CityModel._CityItem&gt; map = 1;</code>
     */

    public _CityItem getMapOrThrow(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, _CityItem> map =
          internalGetMap().getMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetMap(),
          MapDefaultEntryHolder.defaultEntry,
          1);
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<String, _CityItem> entry
           : internalGetMap().getMap().entrySet()) {
        com.google.protobuf.MapEntry<String, _CityItem>
        map__ = MapDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, map__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof _CityModel)) {
        return super.equals(obj);
      }
      _CityModel other = (_CityModel) obj;

      boolean result = true;
      result = result && internalGetMap().equals(
          other.internalGetMap());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetMap().getMap().isEmpty()) {
        hash = (37 * hash) + MAP_FIELD_NUMBER;
        hash = (53 * hash) + internalGetMap().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static _CityModel parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static _CityModel parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static _CityModel parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static _CityModel parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static _CityModel parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static _CityModel parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static _CityModel parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static _CityModel parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static _CityModel parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static _CityModel parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static _CityModel parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static _CityModel parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(_CityModel prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code _CityModel}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:_CityModel)
        _CityModelOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CityModel.internal_static__CityModel_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMap();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableMap();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CityModel.internal_static__CityModel_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                _CityModel.class, Builder.class);
      }

      // Construct using com.wgllss.protobuf.CityModel._CityModel.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        internalGetMutableMap().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CityModel.internal_static__CityModel_descriptor;
      }

      public _CityModel getDefaultInstanceForType() {
        return _CityModel.getDefaultInstance();
      }

      public _CityModel build() {
        _CityModel result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public _CityModel buildPartial() {
        _CityModel result = new _CityModel(this);
        int from_bitField0_ = bitField0_;
        result.map_ = internalGetMap();
        result.map_.makeImmutable();
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof _CityModel) {
          return mergeFrom((_CityModel)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(_CityModel other) {
        if (other == _CityModel.getDefaultInstance()) return this;
        internalGetMutableMap().mergeFrom(
            other.internalGetMap());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        _CityModel parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (_CityModel) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          String, _CityItem> map_;
      private com.google.protobuf.MapField<String, _CityItem>
      internalGetMap() {
        if (map_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              MapDefaultEntryHolder.defaultEntry);
        }
        return map_;
      }
      private com.google.protobuf.MapField<String, _CityItem>
      internalGetMutableMap() {
        onChanged();;
        if (map_ == null) {
          map_ = com.google.protobuf.MapField.newMapField(
              MapDefaultEntryHolder.defaultEntry);
        }
        if (!map_.isMutable()) {
          map_ = map_.copy();
        }
        return map_;
      }

      public int getMapCount() {
        return internalGetMap().getMap().size();
      }
      /**
       * <code>map&lt;string, ._CityModel._CityItem&gt; map = 1;</code>
       */

      public boolean containsMap(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        return internalGetMap().getMap().containsKey(key);
      }
      /**
       * Use {@link #getMapMap()} instead.
       */
      @Deprecated
      public java.util.Map<String, _CityItem> getMap() {
        return getMapMap();
      }
      /**
       * <code>map&lt;string, ._CityModel._CityItem&gt; map = 1;</code>
       */

      public java.util.Map<String, _CityItem> getMapMap() {
        return internalGetMap().getMap();
      }
      /**
       * <code>map&lt;string, ._CityModel._CityItem&gt; map = 1;</code>
       */

      public _CityItem getMapOrDefault(
          String key,
          _CityItem defaultValue) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, _CityItem> map =
            internalGetMap().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, ._CityModel._CityItem&gt; map = 1;</code>
       */

      public _CityItem getMapOrThrow(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, _CityItem> map =
            internalGetMap().getMap();
        if (!map.containsKey(key)) {
          throw new IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearMap() {
        internalGetMutableMap().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, ._CityModel._CityItem&gt; map = 1;</code>
       */

      public Builder removeMap(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        internalGetMutableMap().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @Deprecated
      public java.util.Map<String, _CityItem>
      getMutableMap() {
        return internalGetMutableMap().getMutableMap();
      }
      /**
       * <code>map&lt;string, ._CityModel._CityItem&gt; map = 1;</code>
       */
      public Builder putMap(
          String key,
          _CityItem value) {
        if (key == null) { throw new NullPointerException(); }
        if (value == null) { throw new NullPointerException(); }
        internalGetMutableMap().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, ._CityModel._CityItem&gt; map = 1;</code>
       */

      public Builder putAllMap(
          java.util.Map<String, _CityItem> values) {
        internalGetMutableMap().getMutableMap()
            .putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:_CityModel)
    }

    // @@protoc_insertion_point(class_scope:_CityModel)
    private static final _CityModel DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new _CityModel();
    }

    public static _CityModel getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<_CityModel>
        PARSER = new com.google.protobuf.AbstractParser<_CityModel>() {
      public _CityModel parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new _CityModel(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<_CityModel> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<_CityModel> getParserForType() {
      return PARSER;
    }

    public _CityModel getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static__CityModel_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static__CityModel_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static__CityModel_MapEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static__CityModel_MapEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static__CityModel__CityItem_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static__CityModel__CityItem_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\nCity.proto\"\217\001\n\n_CityModel\022!\n\003map\030\001 \003(\013" +
      "2\024._CityModel.MapEntry\032A\n\010MapEntry\022\013\n\003ke" +
      "y\030\001 \001(\t\022$\n\005value\030\002 \001(\0132\025._CityModel._Cit" +
      "yItem:\0028\001\032\033\n\t_CityItem\022\016\n\006values\030\001 \003(\tB " +
      "\n\023com.wgllss.protobufB\tCityModelb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static__CityModel_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static__CityModel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static__CityModel_descriptor,
        new String[] { "Map", });
    internal_static__CityModel_MapEntry_descriptor =
      internal_static__CityModel_descriptor.getNestedTypes().get(0);
    internal_static__CityModel_MapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static__CityModel_MapEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static__CityModel__CityItem_descriptor =
      internal_static__CityModel_descriptor.getNestedTypes().get(1);
    internal_static__CityModel__CityItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static__CityModel__CityItem_descriptor,
        new String[] { "Values", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
